[workspace]
members = [
    "cli",
    "common",
    "pico-firmware",
]
default-members = ["cli"]
resolver = "2"

[workspace.lints.clippy]
uninlined_format_args = "allow"


[workspace.dependencies]
common = {path = "./common"}

log = "0.4.29"
